### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by jaredcnance** [jaredcnance/dotnet-health#5]
- [x] Get user input `.git` url
- [x] Queue a remote job:
```json
{
  "connectionId": "6ceeffcf-51d8-4ce4-b4b1-44cd83fc2d38",
  "remote": "https://github.com/jaredcnance/dotnet-status.git"
}
```
- [x] [Clone the repository](https://github.com/libgit2/libgit2sharp/)
- [x] Run `dotnet restore` with nuget env vars:
```
$ NUGET_PERSIST_DG=true NUGET_PERSIST_DG_PATH=./out.dg dotnet restore
  Persisting restore input to './out.dg'.
```
  - [Direct execution of CLI](https://github.com/NuGet/NuGet.Client/blob/4a71befbc4ba4f99833b4ad1bde4f4256e9edb13/src/NuGet.Core/NuGet.Test.Utility/CommandRunner.cs)
  - [RestoreRunner](https://github.com/NuGet/NuGet.Client/blob/4a71befbc4ba4f99833b4ad1bde4f4256e9edb13/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs)
- [x] [Parse the dependency graph](https://github.com/NuGet/NuGet.Client/blob/4a71befbc4ba4f99833b4ad1bde4f4256e9edb13/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs), using [Nuget.ProjectModel](https://www.nuget.org/packages/NuGet.ProjectModel/4.3.0-preview3-4168)
- [x] Store repository, project(s), and references. 
Dependency Graph Items of Interest:
  - Projects
    - Name
    - Dependencies (? -- empty)
    - Target Frameworks
      - Dependencies
        - Dependencies
    - Restore Metadata
      - Sources
- [x] Ship status back to UI

**Comment by dasMulli** [comment]
Turns our there is an even easier / "public" way to get the `.dg` file for the solution or project file:
```
dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=graph.dg
```
